# Generated by Django 5.0 on 2024-01-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cuerpo',
            field=models.TextField(max_length=400),
        ),
    ]
