# Generated by Django 5.0.1 on 2024-01-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexBlog', '0005_usuario_first_name_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password2',
        ),
    ]
