# Generated by Django 5.0.1 on 2024-02-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexBlog', '0011_usuario_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
    ]
