# Generated by Django 5.0.1 on 2024-02-03 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexBlog', '0012_remove_usuario_last_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(max_length=200, upload_to='articulo/', verbose_name='Imagen del articulo.'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
