# Generated by Django 5.0.1 on 2024-02-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexBlog', '0013_alter_entrada_autor_alter_entrada_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='autor',
        ),
    ]
