# Generated by Django 5.0.1 on 2024-02-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlexBlog', '0015_entrada_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='imagen',
        ),
    ]
