# Generated by Django 5.0.1 on 2024-02-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlexBlog', '0021_entrada_imagen_alter_entrada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenDefault.jpg', max_length=200, null=True, upload_to='static/imagenes/', verbose_name='Imagen del articulo.'),
        ),
    ]
